version: '3.9'

services:
  schlagenfun-web:
    container_name: schlagenfun-web
    image: schlagenfun:latest
    build: .
    user: appuser
    working_dir: /app
    volumes:
      - /Users/kylesmith/Repos/schlagenfun/instance:/app/instance
    ports:
      - 39655:5000
    env_file:
      - web-variables.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    volumes:
      - /Users/kylesmith/Repos/schlagenfun/instance/postgres:/var/lib/postgresql/data
    env_file:
      - db-variables.env

